apiVersion: v1
kind: Service
metadata:
  name: surveyFormApp-service
spec:
  type: NodePort
  selector:
    app: surveyFormApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
